#!/bin/bash
source cgroup-limits

set -e
set -o pipefail
# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

# Define the maximum memory limit (total_limit - 32MB)
export JAVA_OPTS=${JAVA_OPTS:-"-Xmx$((MEMORY_LIMIT-32))m"}
