#!/bin/bash
source cgroup-limits

set -e
set -o pipefail
# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002
