#!/bin/bash -e

NAME="clojure"
DISPLAY_NAME="Clojure"
FROM="clojure:lein"
TYPE="s2i"
VARIANTS="default"
VERSIONS="jdk8"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
